/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swc.microservice.mission

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
import org.springframework.boot.runApplication

@SpringBootApplication(exclude = [DataSourceAutoConfiguration::class])
open class MissionMicroservice

fun main() {
    runApplication<MissionMicroservice>()
}
