name: Checkout and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'

jobs:
  build-and-test:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3.0.2
      - name: semver
        uses: anitvam/conventionalcommit-semantic-releasing@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get tag
        id: getTag
        run: echo "::set-output name=tagVersion::$(git describe --tags --abbrev=0)"
      - name: Container Registry Authentication
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          docker build . --build-arg service=${{ secrets.CONTAINER_AZURE_SERVICE_PRINCIPAL_NAME }} --build-arg secret=${{ secrets.CONTAINER_AZURE_SECRET }} --build-arg tenant=${{ secrets.CONTAINER_AZURE_TENANT }} --tag ghcr.io/smartwastecollection/mission-microservice:${{ steps.getTag.outputs.tagVersion }}
          docker push ghcr.io/smartwastecollection/mission-microservice:${{ steps.getTag.outputs.tagVersion }}

